//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdCodeGenerator tool.
//     Tool Version:    2.23.427
//     Runtime Version: 4.0.30319.42000
//     Generated on:    2023-04-28 11:35:26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. For more information see http://BlueToque.ca
// </autogenerated>
//------------------------------------------------------------------------------

//	http://BlueToque.ca
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace CodeGeneration.Generators {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BaseCodeGeneratorOptions : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        [field: System.NonSerialized()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private bool generateCodeStringField;
        
        /// <remarks/>
        public bool GenerateCodeString {
            get {
                return this.generateCodeStringField;
            }
            set {
                this.generateCodeStringField = value;
                this.RaisePropertyChanged("GenerateCodeString");
            }
        }
        
        /// <summary />
        private bool generateObjectsField;
        
        /// <remarks/>
        public bool GenerateObjects {
            get {
                return this.generateObjectsField;
            }
            set {
                this.generateObjectsField = value;
                this.RaisePropertyChanged("GenerateObjects");
            }
        }
        
        /// <summary />
        private bool generateObjectsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenerateObjectsSpecified {
            get {
                return this.generateObjectsFieldSpecified;
            }
            set {
                this.generateObjectsFieldSpecified = value;
                this.RaisePropertyChanged("GenerateObjectsSpecified");
            }
        }
        
        /// <summary />
        private bool compileAssemblyField;
        
        /// <remarks/>
        public bool CompileAssembly {
            get {
                return this.compileAssemblyField;
            }
            set {
                this.compileAssemblyField = value;
                this.RaisePropertyChanged("CompileAssembly");
            }
        }
        
        /// <summary />
        private bool compileAssemblyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CompileAssemblySpecified {
            get {
                return this.compileAssemblyFieldSpecified;
            }
            set {
                this.compileAssemblyFieldSpecified = value;
                this.RaisePropertyChanged("CompileAssemblySpecified");
            }
        }
    }
}
#pragma warning restore 1591