//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.21.0
//     Runtime Version: 4.0.30319.1
//     Generated on:    24/07/2010 09:53:21
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace CodeGeneration.Generators {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class XsdClassGeneratorOptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private bool generateObjectsField;
        
        /// <remarks/>
        public bool GenerateObjects {
            get {
                return this.generateObjectsField;
            }
            set {
                this.generateObjectsField = value;
                this.RaisePropertyChanged("GenerateObjects");
            }
        }
        
        /// <summary />
        private bool generateObjectsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenerateObjectsSpecified {
            get {
                return this.generateObjectsFieldSpecified;
            }
            set {
                this.generateObjectsFieldSpecified = value;
                this.RaisePropertyChanged("GenerateObjectsSpecified");
            }
        }
        
        /// <summary />
        private bool compileAssemblyField;
        
        /// <remarks/>
        public bool CompileAssembly {
            get {
                return this.compileAssemblyField;
            }
            set {
                this.compileAssemblyField = value;
                this.RaisePropertyChanged("CompileAssembly");
            }
        }
        
        /// <summary />
        private bool compileAssemblyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CompileAssemblySpecified {
            get {
                return this.compileAssemblyFieldSpecified;
            }
            set {
                this.compileAssemblyFieldSpecified = value;
                this.RaisePropertyChanged("CompileAssemblySpecified");
            }
        }
        
        /// <summary />
        private bool generateComplexTypesField;
        
        /// <remarks/>
        public bool GenerateComplexTypes {
            get {
                return this.generateComplexTypesField;
            }
            set {
                this.generateComplexTypesField = value;
                this.RaisePropertyChanged("GenerateComplexTypes");
            }
        }
        
        /// <summary />
        private bool generateComplexTypesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenerateComplexTypesSpecified {
            get {
                return this.generateComplexTypesFieldSpecified;
            }
            set {
                this.generateComplexTypesFieldSpecified = value;
                this.RaisePropertyChanged("GenerateComplexTypesSpecified");
            }
        }
        
        /// <summary />
        private bool generateCodeStringField;
        
        /// <remarks/>
        public bool GenerateCodeString {
            get {
                return this.generateCodeStringField;
            }
            set {
                this.generateCodeStringField = value;
                this.RaisePropertyChanged("GenerateCodeString");
            }
        }
        
        /// <summary />
        private bool generateCodeStringFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenerateCodeStringSpecified {
            get {
                return this.generateCodeStringFieldSpecified;
            }
            set {
                this.generateCodeStringFieldSpecified = value;
                this.RaisePropertyChanged("GenerateCodeStringSpecified");
            }
        }
        
        /// <summary />
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
    }
}
#pragma warning restore 1591