// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BlueToque.XsdCodeGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "XsdCodeGenerator.VSIX.95c78a75-2f0b-4ab6-a585-dac39bd81d10";
        public const string Name = "XsdCodeGenerator";
        public const string Description = @"Generate code from Xml Schema Documents";
        public const string Language = "en-US";
        public const string Version = "2.23.503";
        public const string Author = "Blue Toque Software";
        public const string Tags = "xml,xsd,code,generator,schema,CSharp";
    }
}
