//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeGeneration.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy class was generated by the Import method.
        /// </summary>
        internal static string NoCodeGenerated {
            get {
                return ResourceManager.GetString("NoCodeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proxy class generated by the Import method includes no methods..
        /// </summary>
        internal static string NoMethodsGenerated {
            get {
                return ResourceManager.GetString("NoMethodsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one optional ServiceDescriptionFormatExtension for the ServiceDescription to be imported has been ignored..
        /// </summary>
        internal static string OptionalExtensionsIgnored {
            get {
                return ResourceManager.GetString("OptionalExtensionsIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one required ServiceDescriptionFormatExtension for the ServiceDescription to be imported has been ignored..
        /// </summary>
        internal static string RequiredExtensionsIgnored {
            get {
                return ResourceManager.GetString("RequiredExtensionsIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a schema validation error while importing the service description..
        /// </summary>
        internal static string SchemaValidation {
            get {
                return ResourceManager.GetString("SchemaValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Binding for the ServiceDescription to be imported is of an unsupported type and has been ignored..
        /// </summary>
        internal static string UnsupportedBindingsIgnored {
            get {
                return ResourceManager.GetString("UnsupportedBindingsIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Operation for the ServiceDescription to be imported is of an unsupported type and has been ignored..
        /// </summary>
        internal static string UnsupportedOperationsIgnored {
            get {
                return ResourceManager.GetString("UnsupportedOperationsIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ServiceDescription to be imported does not conform to the WS-I Basic Profile..
        /// </summary>
        internal static string WsiConformance {
            get {
                return ResourceManager.GetString("WsiConformance", resourceCulture);
            }
        }
    }
}
