//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the BlueToque XsdCodeGenerator tool.
//     Tool Version:    2.23.418.0
//     Runtime Version: 4.0.30319.42000
//     Generated on:    2023-04-19 18:38:09
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. For more information see http://BlueToque.ca
// </autogenerated>
//------------------------------------------------------------------------------

//	http://BlueToque.ca
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace BlueToque.XsdCodeGen.Library {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BlueToque.ca/XsdToClasses.Configuration")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://BlueToque.ca/XsdToClasses.Configuration", IsNullable=false)]
    public partial class Configuration : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private bool enableDataBindingField;
        
        /// <remarks/>
        public bool EnableDataBinding {
            get {
                return this.enableDataBindingField;
            }
            set {
                this.enableDataBindingField = value;
                this.RaisePropertyChanged("EnableDataBinding");
            }
        }
        
        /// <summary />
        private bool generateOrderField;
        
        /// <remarks/>
        public bool GenerateOrder {
            get {
                return this.generateOrderField;
            }
            set {
                this.generateOrderField = value;
                this.RaisePropertyChanged("GenerateOrder");
            }
        }
        
        /// <summary />
        private bool generatePropertiesField;
        
        /// <remarks/>
        public bool GenerateProperties {
            get {
                return this.generatePropertiesField;
            }
            set {
                this.generatePropertiesField = value;
                this.RaisePropertyChanged("GenerateProperties");
            }
        }
        
        /// <summary />
        private bool generateComplexTypesField;
        
        /// <remarks/>
        public bool GenerateComplexTypes {
            get {
                return this.generateComplexTypesField;
            }
            set {
                this.generateComplexTypesField = value;
                this.RaisePropertyChanged("GenerateComplexTypes");
            }
        }
        
        /// <summary />
        private bool generateComplexTypesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenerateComplexTypesSpecified {
            get {
                return this.generateComplexTypesFieldSpecified;
            }
            set {
                this.generateComplexTypesFieldSpecified = value;
                this.RaisePropertyChanged("GenerateComplexTypesSpecified");
            }
        }
        
        /// <summary />
        private AssemblyTypeCollection codeModifiersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CodeModifier", IsNullable=false)]
        public AssemblyTypeCollection CodeModifiers {
            get {
                return this.codeModifiersField;
            }
            set {
                this.codeModifiersField = value;
                this.RaisePropertyChanged("CodeModifiers");
            }
        }
        
        /// <summary />
        private AssemblyTypeCollection schemaImporterExtensionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SchemaImporterExtension", IsNullable=false)]
        public AssemblyTypeCollection SchemaImporterExtensions {
            get {
                return this.schemaImporterExtensionsField;
            }
            set {
                this.schemaImporterExtensionsField = value;
                this.RaisePropertyChanged("SchemaImporterExtensions");
            }
        }
        
        /// <summary />
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/XsdToClasses.Configuration")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://BlueToque.ca/XsdToClasses.Configuration", IsNullable=true)]
    public partial class AssemblyType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <summary />
        private string assemblyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
                this.RaisePropertyChanged("Assembly");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/XsdToClasses.Configuration")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://BlueToque.ca/XsdToClasses.Configuration", IsNullable=true)]
    public partial class CodeModifiersType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private AssemblyTypeCollection codeModifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CodeModifier")]
        public AssemblyTypeCollection CodeModifier {
            get {
                return this.codeModifierField;
            }
            set {
                this.codeModifierField = value;
                this.RaisePropertyChanged("CodeModifier");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/XsdToClasses.Configuration")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://BlueToque.ca/XsdToClasses.Configuration", IsNullable=true)]
    public partial class SchemaImporterExtensionsType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private AssemblyTypeCollection schemaImporterExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SchemaImporterExtension")]
        public AssemblyTypeCollection SchemaImporterExtension {
            get {
                return this.schemaImporterExtensionField;
            }
            set {
                this.schemaImporterExtensionField = value;
                this.RaisePropertyChanged("SchemaImporterExtension");
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/XsdToClasses.Configuration")]
    public partial class AssemblyTypeCollection : System.Collections.Generic.List<AssemblyType> {
    }
}
#pragma warning restore 1591