//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdCodeGenerator, Version=2.23.503.0, Culture=neutral, PublicKeyToken=930d621ce8556c2f tool.
//     Tool Version:    2.23.503.0
//     Runtime Version: 4.0.30319.42000
//     Generated on:    2023-06-01 14:57:35
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. For more information see http://BlueToque.ca
// </autogenerated>
//------------------------------------------------------------------------------

//	http://BlueToque.ca
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace XsdCodeGenerator.Test.Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/Example/Data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://BlueToque.ca/Example/Data", IsNullable=true)]
    public partial class Data : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        [field: System.NonSerialized()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private DataTypeCollection dataCollectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Data", IsNullable=false)]
        public DataTypeCollection DataCollection {
            get {
                return this.dataCollectionField;
            }
            set {
                this.dataCollectionField = value;
                this.RaisePropertyChanged("DataCollection");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/Example/Data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://BlueToque.ca/Example/Data", IsNullable=true)]
    public partial class DataType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        [field: System.NonSerialized()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private DataTypeCollection dataCollectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Data", IsNullable=false)]
        public DataTypeCollection DataCollection {
            get {
                return this.dataCollectionField;
            }
            set {
                this.dataCollectionField = value;
                this.RaisePropertyChanged("DataCollection");
            }
        }
        
        /// <summary />
        [System.NonSerialized()]
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <summary />
        private int indexField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
                this.RaisePropertyChanged("Index");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DataGroup", Namespace="http://BlueToque.ca/Example/Data")]
    [System.Xml.Serialization.XmlRootAttribute("DataGroup", Namespace="http://BlueToque.ca/Example/Data", IsNullable=true)]
    public partial class DataGroup1 : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        [field: System.NonSerialized()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private DataTypeCollection dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Data")]
        public DataTypeCollection Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BlueToque.ca/Example/Data")]
    public partial class DataTypeCollection : System.Collections.Generic.List<DataType> {
    }
}
#pragma warning restore 1591